version: "3.6"

services:
  social-app-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: api
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=db
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
      - MONGO_DB=$MONGO_DB_ERROR
      - JWT_SECRET_KEY=$JWT_SECRET_KEY
      - LOG_LEVEL=$LOG_LEVEL
    ports:
      - "5000:5000"
    volumes:
      - .:/home/node/server
      - node_modules:/home/node/server/node_modules
    networks:
      - app-network
    command: ./wait-for.sh db:27017 -- /home/node/server/node_modules/.bin/nodemon server.js
    depends_on:
      - db

  db:
    image: mongo:4.1.9-xenial
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - dbdata:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:
