services:
  api:
    build: ./
    container_name: api
    restart: unless-stopped
    environment:
      JWT_SECRET_KEY: verysecretkey
      LOG_LEVEL: debug
      DB_URL: mongodb://db/social
    ports:
      - 3001:3001
    volumes:
      - .:/app
  db:
    image: mongo:5
    container_name: db
    ports:
      - 27017:27017
    restart: unless-stopped
    volumes:
      - social:/data/db
volumes:
  social:
